name: page-analyzer

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Clone repository
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: | 
          pip install poetry
          poetry install
      - name: Run tests
        run: |
          make test
        